// Generated by CoffeeScript 1.4.0
/* Version: 0.1
*/

/* Author: Sun Yunrui
*/

var express = require('express');
var controller = require('./controllers');
var http = require('http');
var app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser({
    defer: true
  }));
  app.use(express.methodOverride());
  app.use(app.router);
  app.set('development', function() {
    return express.errorHandler();
  });
});

app.get("/", controller.index);
// read an image
app.get(/^\/image\/([a-z0-9]+)_(\d+).(jpg|png|JPG|jpeg|gif)?/, controller.image);
// upload an image
app.get('/form', controller.form);
app.post('/upload', controller.upload);
app.get('/404_error', controller.errors);

http.createServer(app).listen(app.get('port'), function() {
  console.log("Express server listening on port " + app.get('port'));
});
